' Bright branded colors
!define _DARKGRAY        #3A3A3A
!define _LIGHTBLUE       #1BA3DD
!define _SEA             #B7D8D9
!define _LIME            #C1D831
!define _LEMON           #FEDD00
!define _PURPLE          #7D4F9F
!define _WHITE           #FFFFFF

' Color variants
!define _SOFTLIGHTBLUE   #83CEE7
!define _DARKSEA         #93ACAD

' Aliases
!define _BORDER          SEA
!define _FILL            SEA
!define _FILLCONTAINER   WHITE   
!define _ENDPOINT        DARKGRAY
!define _TRANSITION      SEA
!define _TEXT            BLACK
!define _MUTEDTEXT       DARKSEA

'Diagram
skinparam shadowing false
skinparam DefaultFontName Proxima Nova
skinparam ArrowColor _TRANSITION
skinparam BackgroundColor _WHITE
'skinparam DiagramBorderColor

' Text
skinparam DefaultFontColor _TEXT
skinparam ArrowFontColor _MUTEDTEXT

' BorderColor
skinparam ActivityBorderColor _BORDER
skinparam ActivityDiamondBorderColor _BORDER
skinparam ActorBorderColor _BORDER
skinparam AgentBorderColor _BORDER
skinparam ArtifactBorderColor _BORDER
skinparam CardBorderColor _BORDER
skinparam ClassBorderColor _BORDER
skinparam CloudBorderColor _BORDER
skinparam CollectionsBorderColor _BORDER
skinparam ComponentBorderColor _BORDER
skinparam ControlBorderColor _BORDER
skinparam BoundaryBorderColor _BORDER
skinparam DatabaseBorderColor _BORDER
skinparam EntityBorderColor _BORDER
skinparam FileBorderColor _BORDER
skinparam FolderBorderColor _BORDER
skinparam FrameBorderColor _BORDER
skinparam InterfaceBorderColor _BORDER
skinparam LegendBorderColor _BORDER
skinparam NodeBorderColor _BORDER
skinparam NoteBorderColor _BORDER
skinparam ObjectBorderColor _BORDER
skinparam PackageBorderColor _BORDER
skinparam PageBorderColor _BORDER
skinparam ParticipantBorderColor _BORDER
skinparam PartitionBorderColor _ENDPOINT
skinparam QueueBorderColor _BORDER
skinparam RectangleBorderColor _BORDER
skinparam SequenceBoxBorderColor _BORDER
skinparam SequenceDividerBorderColor _BORDER
skinparam SequenceGroupBorderColor _BORDER
skinparam SequenceLifeLineBorderColor _BORDER
skinparam SequenceReferenceBorderColor _BORDER
skinparam StackBorderColor _BORDER
skinparam StateBorderColor _BORDER
skinparam StereotypeABorderColor _BORDER
skinparam StereotypeCBorderColor _BORDER
skinparam StereotypeEBorderColor _BORDER
skinparam StereotypeIBorderColor _BORDER
skinparam StereotypeNBorderColor _BORDER
skinparam StorageBorderColor _BORDER
skinparam SwimlaneBorderColor _BORDER
skinparam UsecaseBorderColor _BORDER

' BackgroundColor
skinparam ActivityBackgroundColor _FILL
skinparam ActivityDiamondBackgroundColor _FILL
skinparam ActorBackgroundColor _FILL
skinparam AgentBackgroundColor _FILL
skinparam ArtifactBackgroundColor _FILL
skinparam BoundaryBackgroundColor _FILL
skinparam CardBackgroundColor _FILL
skinparam ClassBackgroundColor _FILL
skinparam ClassHeaderBackgroundColor _FILL
skinparam CloudBackgroundColor _FILL
skinparam CollectionsBackgroundColor _FILL
skinparam ComponentBackgroundColor _FILL
skinparam BoundaryBackgroundColor _FILL
skinparam ControlBackgroundColor _FILL
skinparam DatabaseBackgroundColor _FILL
skinparam EntityBackgroundColor _FILL
skinparam FileBackgroundColor _FILL
skinparam FolderBackgroundColor _FILL
skinparam FrameBackgroundColor _FILL
skinparam IconPackageBackgroundColor _FILL
skinparam IconPrivateBackgroundColor _FILL
skinparam IconProtectedBackgroundColor _FILL
skinparam IconPublicBackgroundColor _FILL
skinparam InterfaceBackgroundColor _FILL
skinparam LegendBackgroundColor _FILL
skinparam NodeBackgroundColor _FILL
skinparam NoteBackgroundColor _FILL
skinparam ObjectBackgroundColor _FILL
skinparam PackageBackgroundColor _FILL
skinparam ParticipantBackgroundColor _FILL
skinparam PartitionBackgroundColor _FILLCONTAINER
skinparam QueueBackgroundColor _FILL
skinparam RectangleBackgroundColor _FILL
skinparam SequenceBoxBackgroundColor _FILL
skinparam SequenceDividerBackgroundColor _FILL
skinparam SequenceGroupBackgroundColor _FILL
skinparam SequenceGroupBodyBackgroundColor _FILL
skinparam SequenceLifeLineBackgroundColor _FILL
skinparam SequenceReferenceBackgroundColor _FILL
skinparam SequenceReferenceHeaderBackgroundColor _FILL
skinparam StackBackgroundColor _FILL
skinparam StateBackgroundColor _FILL
skinparam StereotypeABackgroundColor _FILL
skinparam StereotypeCBackgroundColor _FILL
skinparam StereotypeEBackgroundColor _FILL
skinparam StereotypeIBackgroundColor _FILL
skinparam StereotypeNBackgroundColor _FILL
skinparam StorageBackgroundColor _FILL
skinparam TitleBackgroundColor _FILL
skinparam UsecaseBackgroundColor _FILL

' Start- and Endpoints
skinparam ActivityStartColor _ENDPOINT
skinparam ActivityEndColor _ENDPOINT
skinparam StateStartColor _ENDPOINT
skinparam StateEndColor _ENDPOINT
