' Bright branded colors
!define DARKGRAY        #3A3A3A
!define LIGHTBLUE       #1BA3DD
!define SEA             #B7D8D9
!define LIME            #C1D831
!define LEMON           #FEDD00
!define PURPLE          #7D4F9F
!define WHITE           #FFFFFF

' Color variants
!define SOFTLIGHTBLUE   #83CEE7
!define DARKSEA         #93ACAD

' Aliases
!define BORDER          SEA
!define FILL            SEA
!define FILLCONTAINER   WHITE   
!define ENDPOINT        DARKGRAY
!define TRANSITION      SEA
!define TEXT            BLACK
!define MUTEDTEXT       DARKSEA

'Diagram
skinparam shadowing false
skinparam DefaultFontName Proxima Nova
skinparam ArrowColor TRANSITION
skinparam BackgroundColor white
'skinparam DiagramBorderColor

' Text
skinparam DefaultFontColor TEXT
skinparam ArrowFontColor MUTEDTEXT

' BorderColor
skinparam ActivityBorderColor BORDER
skinparam ActivityDiamondBorderColor BORDER
skinparam ActorBorderColor BORDER
skinparam AgentBorderColor BORDER
skinparam ArtifactBorderColor BORDER
skinparam CardBorderColor BORDER
skinparam ClassBorderColor BORDER
skinparam CloudBorderColor BORDER
skinparam CollectionsBorderColor BORDER
skinparam ComponentBorderColor BORDER
skinparam ControlBorderColor BORDER
skinparam BoundaryBorderColor BORDER
skinparam DatabaseBorderColor BORDER
skinparam EntityBorderColor BORDER
skinparam FileBorderColor BORDER
skinparam FolderBorderColor BORDER
skinparam FrameBorderColor BORDER
skinparam InterfaceBorderColor BORDER
skinparam LegendBorderColor BORDER
skinparam NodeBorderColor BORDER
skinparam NoteBorderColor BORDER
skinparam ObjectBorderColor BORDER
skinparam PackageBorderColor BORDER
skinparam PageBorderColor BORDER
skinparam ParticipantBorderColor BORDER
skinparam PartitionBorderColor ENDPOINT
skinparam QueueBorderColor BORDER
skinparam RectangleBorderColor BORDER
skinparam SequenceBoxBorderColor BORDER
skinparam SequenceDividerBorderColor BORDER
skinparam SequenceGroupBorderColor BORDER
skinparam SequenceLifeLineBorderColor BORDER
skinparam SequenceReferenceBorderColor BORDER
skinparam StackBorderColor BORDER
skinparam StateBorderColor BORDER
skinparam StereotypeABorderColor BORDER
skinparam StereotypeCBorderColor BORDER
skinparam StereotypeEBorderColor BORDER
skinparam StereotypeIBorderColor BORDER
skinparam StereotypeNBorderColor BORDER
skinparam StorageBorderColor BORDER
skinparam SwimlaneBorderColor BORDER
skinparam UsecaseBorderColor BORDER

' BackgroundColor
skinparam ActivityBackgroundColor FILL
skinparam ActivityDiamondBackgroundColor FILL
skinparam ActorBackgroundColor FILL
skinparam AgentBackgroundColor FILL
skinparam ArtifactBackgroundColor FILL
skinparam BoundaryBackgroundColor FILL
skinparam CardBackgroundColor FILL
skinparam ClassBackgroundColor FILL
skinparam ClassHeaderBackgroundColor FILL
skinparam CloudBackgroundColor FILL
skinparam CollectionsBackgroundColor FILL
skinparam ComponentBackgroundColor FILL
skinparam BoundaryBackgroundColor FILL
skinparam ControlBackgroundColor FILL
skinparam DatabaseBackgroundColor FILL
skinparam EntityBackgroundColor FILL
skinparam FileBackgroundColor FILL
skinparam FolderBackgroundColor FILL
skinparam FrameBackgroundColor FILL
skinparam IconPackageBackgroundColor FILL
skinparam IconPrivateBackgroundColor FILL
skinparam IconProtectedBackgroundColor FILL
skinparam IconPublicBackgroundColor FILL
skinparam InterfaceBackgroundColor FILL
skinparam LegendBackgroundColor FILL
skinparam NodeBackgroundColor FILL
skinparam NoteBackgroundColor FILL
skinparam ObjectBackgroundColor FILL
skinparam PackageBackgroundColor FILL
skinparam ParticipantBackgroundColor FILL
skinparam PartitionBackgroundColor FILLCONTAINER
skinparam QueueBackgroundColor FILL
skinparam RectangleBackgroundColor FILL
skinparam SequenceBoxBackgroundColor FILL
skinparam SequenceDividerBackgroundColor FILL
skinparam SequenceGroupBackgroundColor FILL
skinparam SequenceGroupBodyBackgroundColor FILL
skinparam SequenceLifeLineBackgroundColor FILL
skinparam SequenceReferenceBackgroundColor FILL
skinparam SequenceReferenceHeaderBackgroundColor FILL
skinparam StackBackgroundColor FILL
skinparam StateBackgroundColor FILL
skinparam StereotypeABackgroundColor FILL
skinparam StereotypeCBackgroundColor FILL
skinparam StereotypeEBackgroundColor FILL
skinparam StereotypeIBackgroundColor FILL
skinparam StereotypeNBackgroundColor FILL
skinparam StorageBackgroundColor FILL
skinparam TitleBackgroundColor FILL
skinparam UsecaseBackgroundColor FILL

' Start- and Endpoints
skinparam ActivityStartColor ENDPOINT
skinparam ActivityEndColor ENDPOINT
skinparam StateStartColor ENDPOINT
skinparam StateEndColor ENDPOINT
