' NOTE that those are NOT underscores, but unicode UNDER BARs: _

' Bright branded colors
!define COL_DARKGRAY        #3A3A3A
!define COL_LIGHTBLUE       #1BA3DD
!define COL_SEA             #B7D8D9
!define COL_LIME            #C1D831
!define COL_LEMON           #FEDD00
!define COL_PURPLE          #7D4F9F
!define COL_WHITE           #FFFFFF

' Color variants
!define COL_SOFTLIGHTBLUE   #83CEE7
!define COL_DARKSEA         #93ACAD

' Aliases
!define COL_BORDER          COL_SEA
!define COL_FILL            COL_SEA
!define COL_FILLCONTAINER   COL_WHITE   
!define COL_ENDPOINT        COL_DARKGRAY
!define COL_TRANSITION      COL_SEA
!define COL_TEXT            COL_BLACK
!define COL_MUTEDTEXT       COL_DARKSEA

'Diagram
skinparam shadowing false
skinparam DefaultFontName Proxima Nova
skinparam ArrowColor COL_TRANSITION
skinparam BackgroundColor white
'skinparam DiagramBorderColor

' Text
skinparam DefaultFontColor COL_TEXT
skinparam ArrowFontColor COL_MUTEDTEXT

' BorderColor
skinparam ActivityBorderColor COL_BORDER
skinparam ActivityDiamondBorderColor COL_BORDER
skinparam ActorBorderColor COL_BORDER
skinparam AgentBorderColor COL_BORDER
skinparam ArtifactBorderColor COL_BORDER
skinparam CardBorderColor COL_BORDER
skinparam ClassBorderColor COL_BORDER
skinparam CloudBorderColor COL_BORDER
skinparam CollectionsBorderColor COL_BORDER
skinparam ComponentBorderColor COL_BORDER
skinparam ControlBorderColor COL_BORDER
skinparam BoundaryBorderColor COL_BORDER
skinparam DatabaseBorderColor COL_BORDER
skinparam EntityBorderColor COL_BORDER
skinparam FileBorderColor COL_BORDER
skinparam FolderBorderColor COL_BORDER
skinparam FrameBorderColor COL_BORDER
skinparam InterfaceBorderColor COL_BORDER
skinparam LegendBorderColor COL_BORDER
skinparam NodeBorderColor COL_BORDER
skinparam NoteBorderColor COL_BORDER
skinparam ObjectBorderColor COL_BORDER
skinparam PackageBorderColor COL_BORDER
skinparam PageBorderColor COL_BORDER
skinparam ParticipantBorderColor COL_BORDER
skinparam PartitionBorderColor COL_ENDPOINT
skinparam QueueBorderColor COL_BORDER
skinparam RectangleBorderColor COL_BORDER
skinparam SequenceBoxBorderColor COL_BORDER
skinparam SequenceDividerBorderColor COL_BORDER
skinparam SequenceGroupBorderColor COL_BORDER
skinparam SequenceLifeLineBorderColor COL_BORDER
skinparam SequenceReferenceBorderColor COL_BORDER
skinparam StackBorderColor COL_BORDER
skinparam StateBorderColor COL_BORDER
skinparam StereotypeABorderColor COL_BORDER
skinparam StereotypeCBorderColor COL_BORDER
skinparam StereotypeEBorderColor COL_BORDER
skinparam StereotypeIBorderColor COL_BORDER
skinparam StereotypeNBorderColor COL_BORDER
skinparam StorageBorderColor COL_BORDER
skinparam SwimlaneBorderColor COL_BORDER
skinparam UsecaseBorderColor COL_BORDER

' BackgroundColor
skinparam ActivityBackgroundColor COL_FILL
skinparam ActivityDiamondBackgroundColor COL_FILL
skinparam ActorBackgroundColor COL_FILL
skinparam AgentBackgroundColor COL_FILL
skinparam ArtifactBackgroundColor COL_FILL
skinparam BoundaryBackgroundColor COL_FILL
skinparam CardBackgroundColor COL_FILL
skinparam ClassBackgroundColor COL_FILL
skinparam ClassHeaderBackgroundColor COL_FILL
skinparam CloudBackgroundColor COL_FILL
skinparam CollectionsBackgroundColor COL_FILL
skinparam ComponentBackgroundColor COL_FILL
skinparam BoundaryBackgroundColor COL_FILL
skinparam ControlBackgroundColor COL_FILL
skinparam DatabaseBackgroundColor COL_FILL
skinparam EntityBackgroundColor COL_FILL
skinparam FileBackgroundColor COL_FILL
skinparam FolderBackgroundColor COL_FILL
skinparam FrameBackgroundColor COL_FILL
skinparam IconPackageBackgroundColor COL_FILL
skinparam IconPrivateBackgroundColor COL_FILL
skinparam IconProtectedBackgroundColor COL_FILL
skinparam IconPublicBackgroundColor COL_FILL
skinparam InterfaceBackgroundColor COL_FILL
skinparam LegendBackgroundColor COL_FILL
skinparam NodeBackgroundColor COL_FILL
skinparam NoteBackgroundColor COL_FILL
skinparam ObjectBackgroundColor COL_FILL
skinparam PackageBackgroundColor COL_FILL
skinparam ParticipantBackgroundColor COL_FILL
skinparam PartitionBackgroundColor COL_FILLCONTAINER
skinparam QueueBackgroundColor COL_FILL
skinparam RectangleBackgroundColor COL_FILL
skinparam SequenceBoxBackgroundColor COL_FILL
skinparam SequenceDividerBackgroundColor COL_FILL
skinparam SequenceGroupBackgroundColor COL_FILL
skinparam SequenceGroupBodyBackgroundColor COL_FILL
skinparam SequenceLifeLineBackgroundColor COL_FILL
skinparam SequenceReferenceBackgroundColor COL_FILL
skinparam SequenceReferenceHeaderBackgroundColor COL_FILL
skinparam StackBackgroundColor COL_FILL
skinparam StateBackgroundColor COL_FILL
skinparam StereotypeABackgroundColor COL_FILL
skinparam StereotypeCBackgroundColor COL_FILL
skinparam StereotypeEBackgroundColor COL_FILL
skinparam StereotypeIBackgroundColor COL_FILL
skinparam StereotypeNBackgroundColor COL_FILL
skinparam StorageBackgroundColor COL_FILL
skinparam TitleBackgroundColor COL_FILL
skinparam UsecaseBackgroundColor COL_FILL

' Start- and Endpoints
skinparam ActivityStartColor COL_ENDPOINT
skinparam ActivityEndColor COL_ENDPOINT
skinparam StateStartColor COL_ENDPOINT
skinparam StateEndColor COL_ENDPOINT
